defaultPlacement: end
enableVersioning: true
entryTypes:
  - 23e803e7-2d41-4653-a32d-e9cc5874da7e # Locations
handle: locations
maxAuthors: 1
name: Locations
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: true
    template: locations/_entry.twig
    uriFormat: 'locations/{slug}'
structure:
  maxLevels: null
  uid: 3694ac94-0329-4339-9bf3-cc0ffb2e99b7
type: structure
